# Generated by Django 5.2.1 on 2025-12-22 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AddField(
            model_name='membershipperiod',
            name='applied_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_periods', to='gyms.plan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='applied_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gyms.plan'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['member', '-payment_date'], name='gyms_paymen_member__843d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['applied_plan', '-payment_date'], name='gyms_paymen_applied_564d32_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_no'], name='gyms_paymen_receipt_848eb1_idx'),
        ),
    ]
