# Generated by Django 5.2.9 on 2025-12-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_alter_payment_options_membershipperiod_applied_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='gyms_paymen_member__843d8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='gyms_paymen_applied_564d32_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='gyms_paymen_receipt_848eb1_idx',
        ),
        migrations.RemoveField(
            model_name='membershipperiod',
            name='applied_plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='applied_plan',
        ),
    ]
